import EventEmitter from "eventemitter3";

export const eventEmitter = new EventEmitter();

export enum EVENT_TYPE {
	ACTIVITY_CONFIG_UPDATED = 'ACTIVITY_CONFIG_UPDATED',
	ACTIVITY_CONFIG_GET = 'ACTIVITY_CONFIG_GET',
	ACTIVITY_CONFIG_TRANSFER = 'ACTIVITY_CONFIG_TRANSFER',
	ACTIVITY_SPEC_UPDATED = 'ACTIVITY_SPEC_UPDATED',
	ACTIVITY_SPEC_GET = 'ACTIVITY_SPEC_GET',
	ACTIVITY_SPEC_TRANSFER = 'ACTIVITY_SPEC_TRANSFER'
}